import { AITool } from '../types';

export const AI_TOOLS_LIST: AITool[] = [
  {
    id: 'bg-remover',
    name: 'Background Remover',
    category: 'erase',
    description: 'Instant 1-click automatic background removal with crisp cutout edges.',
    iconName: 'Scissors',
    gradient: ['#5B5FEF', '#7C4DFF'],
    isComingSoon: false,
    isPopular: true,
    badgeText: 'Popular',
  },
  {
    id: 'object-eraser',
    name: 'Object Eraser',
    category: 'erase',
    description: 'Cleanly wipe away unwanted objects, people, or imperfections.',
    iconName: 'Eraser',
    gradient: ['#EC4899', '#8B5CF6'],
    isComingSoon: false,
    isPopular: true,
  },
  {
    id: 'image-enhancer',
    name: 'Image Enhancer',
    category: 'enhance',
    description: 'Auto-balance lighting, contrast, and color vibrancy in HD.',
    iconName: 'Sparkles',
    gradient: ['#10B981', '#059669'],
    isComingSoon: false,
    badgeText: 'AI Powered',
  },
  {
    id: 'upscale',
    name: 'AI Upscale 4K',
    category: 'enhance',
    description: 'Enlarge small images up to 4x resolution without quality loss.',
    iconName: 'Maximize2',
    gradient: ['#3B82F6', '#1D4ED8'],
    isComingSoon: false,
    isPopular: true,
  },
  {
    id: 'color-correction',
    name: 'Color Correction',
    category: 'adjust',
    description: 'Professional color grading matched to cinematic color palettes.',
    iconName: 'Palette',
    gradient: ['#F59E0B', '#D97706'],
    isComingSoon: false,
  },
  {
    id: 'magic-erase',
    name: 'Magic Erase Pro',
    category: 'erase',
    description: 'Smart brush tool that intelligently reconstructs backgrounds.',
    iconName: 'Wand2',
    gradient: ['#8B5CF6', '#D946EF'],
    isComingSoon: true,
    badgeText: 'Coming Soon',
  },
  {
    id: 'portrait-enhance',
    name: 'Portrait Enhance',
    category: 'portrait',
    description: 'Smooth skin, brighten eyes, and refine studio lighting.',
    iconName: 'UserCheck',
    gradient: ['#F43F5E', '#FB7185'],
    isComingSoon: false,
    isPopular: true,
  },
  {
    id: 'face-restore',
    name: 'Face Restore',
    category: 'portrait',
    description: 'Fix blurry faces in old or low-resolution portrait photographs.',
    iconName: 'Smile',
    gradient: ['#06B6D4', '#0891B2'],
    isComingSoon: false,
  },
  {
    id: 'ai-relight',
    name: 'AI Relight',
    category: 'portrait',
    description: 'Add virtual studio spotlights and soft directional ambient light.',
    iconName: 'Sun',
    gradient: ['#EAB308', '#CA8A04'],
    isComingSoon: true,
    badgeText: 'Coming Soon',
  },
  {
    id: 'sky-replacement',
    name: 'Sky Replacement',
    category: 'generative',
    description: 'Swap overcast skies with vibrant sunsets, starry nights, or clouds.',
    iconName: 'CloudSun',
    gradient: ['#0284C7', '#38BDF8'],
    isComingSoon: false,
  },
  {
    id: 'remove-text',
    name: 'Remove Text',
    category: 'erase',
    description: 'Detect and erase watermarks, logos, and typography cleanly.',
    iconName: 'FileText',
    gradient: ['#64748B', '#334155'],
    isComingSoon: false,
  },
  {
    id: 'shadow-generator',
    name: 'Shadow Generator',
    category: 'generative',
    description: 'Cast realistic 3D drop shadows under subjects and products.',
    iconName: 'Layers',
    gradient: ['#475569', '#1E293B'],
    isComingSoon: true,
    badgeText: 'Coming Soon',
  },
  {
    id: 'reflection-generator',
    name: 'Reflection Generator',
    category: 'generative',
    description: 'Create glossy ground reflections for luxury ecommerce photos.',
    iconName: 'Copy',
    gradient: ['#6366F1', '#4F46E5'],
    isComingSoon: true,
    badgeText: 'Coming Soon',
  },
  {
    id: 'generative-fill',
    name: 'Generative Fill',
    category: 'generative',
    description: 'Insert new elements or change outfits using text prompts.',
    iconName: 'Paintbrush',
    gradient: ['#A855F7', '#7E22CE'],
    isComingSoon: true,
    isNew: true,
    badgeText: 'Pro',
  },
  {
    id: 'expand-image',
    name: 'Expand Image (Outpainting)',
    category: 'generative',
    description: 'Extend image borders seamlessly to fits any aspect ratio.',
    iconName: 'Scaling',
    gradient: ['#14B8A6', '#0D9488'],
    isComingSoon: true,
    badgeText: 'Coming Soon',
  },
  {
    id: 'crop-resize',
    name: 'Crop & Resize',
    category: 'adjust',
    description: 'Presets for Instagram, TikTok, YouTube thumbnails, and stories.',
    iconName: 'Crop',
    gradient: ['#F97316', '#EA580C'],
    isComingSoon: false,
  },
  {
    id: 'compress-image',
    name: 'Compress Image',
    category: 'adjust',
    description: 'Reduce file size by up to 90% without visible loss in quality.',
    iconName: 'Minimize2',
    gradient: ['#84CC16', '#65A30D'],
    isComingSoon: false,
  },
  {
    id: 'blur-background',
    name: 'Blur Background',
    category: 'portrait',
    description: 'DSLR bokeh depth-of-field effect with customizable aperture.',
    iconName: 'EyeOff',
    gradient: ['#EC4899', '#DB2777'],
    isComingSoon: false,
  },
  {
    id: 'product-photography',
    name: 'Product Studio AI',
    category: 'generative',
    description: 'Place your items on luxury studio pedestals and podiums.',
    iconName: 'ShoppingBag',
    gradient: ['#10B981', '#047857'],
    isComingSoon: false,
    badgeText: 'Ecommerce',
  },
  {
    id: 'cartoon-style',
    name: 'Cartoon Style',
    category: 'style',
    description: 'Transform photos into 3D Pixar & comic book illustrations.',
    iconName: 'Image',
    gradient: ['#F43F5E', '#E11D48'],
    isComingSoon: false,
  },
  {
    id: 'anime-style',
    name: 'Anime Style Filter',
    category: 'style',
    description: 'Turn scenery and selfies into Makoto Shinkai anime art.',
    iconName: 'Zap',
    gradient: ['#8B5CF6', '#6D28D9'],
    isComingSoon: false,
  },
  {
    id: 'old-photo-restore',
    name: 'Old Photo Restore',
    category: 'enhance',
    description: 'Colorize vintage black-and-white photos & remove scratches.',
    iconName: 'History',
    gradient: ['#D97706', '#92400E'],
    isComingSoon: false,
  },
  {
    id: 'style-transfer',
    name: 'Artistic Style Transfer',
    category: 'style',
    description: 'Paint your photos in the style of Van Gogh, Monet, or Picasso.',
    iconName: 'Brush',
    gradient: ['#06B6D4', '#0284C7'],
    isComingSoon: true,
    badgeText: 'Coming Soon',
  },
  {
    id: 'ai-avatar',
    name: 'AI Avatar Generator',
    category: 'portrait',
    description: 'Generate 50+ unique studio avatars from 10 selfie uploads.',
    iconName: 'User',
    gradient: ['#E11D48', '#BE123C'],
    isComingSoon: true,
    badgeText: 'Pro',
  }
];
