import { AITool } from '../types';

export const AI_TOOLS_LIST: AITool[] = [
  {
    id: 'bg-remover',
    name: 'Background Remover',
    category: 'erase',
    description: 'Instant 1-click automatic background removal with crisp cutout edges.',
    iconName: 'Scissors',
    gradient: ['#6C4DFF', '#8B5CF6'],
    isComingSoon: false,
  },
  {
    id: 'object-eraser',
    name: 'Object Eraser',
    category: 'erase',
    description: 'Cleanly wipe away unwanted objects, people, or imperfections.',
    iconName: 'Eraser',
    gradient: ['#EC4899', '#8B5CF6'],
    isComingSoon: false,
  },
  {
    id: 'image-enhancer',
    name: 'Image Enhancer',
    category: 'enhance',
    description: 'Auto-balance lighting, contrast, and color vibrancy in HD.',
    iconName: 'Sparkles',
    gradient: ['#10B981', '#059669'],
    isComingSoon: false,
  },
  {
    id: 'upscale',
    name: 'AI Upscale 4K',
    category: 'enhance',
    description: 'Enlarge small images up to 4x resolution without quality loss.',
    iconName: 'ArrowUpSquare',
    gradient: ['#3B82F6', '#1D4ED8'],
    isComingSoon: false,
  },
  {
    id: 'portrait-enhance',
    name: 'Portrait Enhance',
    category: 'portrait',
    description: 'Smooth skin, brighten eyes, and refine studio lighting.',
    iconName: 'UserRound',
    gradient: ['#F43F5E', '#FB7185'],
    isComingSoon: false,
  },
  {
    id: 'face-restore',
    name: 'Face Restore',
    category: 'portrait',
    description: 'Fix blurry faces in old or low-resolution portrait photographs.',
    iconName: 'Smile',
    gradient: ['#06B6D4', '#0891B2'],
    isComingSoon: false,
  },
  {
    id: 'color-correction',
    name: 'Color Correction',
    category: 'adjust',
    description: 'Professional color grading matched to cinematic color palettes.',
    iconName: 'Palette',
    gradient: ['#F59E0B', '#D97706'],
    isComingSoon: false,
  },
  {
    id: 'sky-replacement',
    name: 'Sky Replacement',
    category: 'generative',
    description: 'Swap overcast skies with vibrant sunsets, starry nights, or clouds.',
    iconName: 'Cloud',
    gradient: ['#0284C7', '#38BDF8'],
    isComingSoon: false,
  },
  {
    id: 'expand-image',
    name: 'Expand Image',
    category: 'generative',
    description: 'Extend image borders seamlessly to fit any aspect ratio.',
    iconName: 'Maximize',
    gradient: ['#14B8A6', '#0D9488'],
    isComingSoon: false,
  },
  {
    id: 'cartoon-style',
    name: 'Cartoon Style',
    category: 'style',
    description: 'Transform photos into 3D Pixar & comic book illustrations.',
    iconName: 'Paintbrush',
    gradient: ['#F43F5E', '#E11D48'],
    isComingSoon: false,
  },
  {
    id: 'anime-style',
    name: 'Anime Style',
    category: 'style',
    description: 'Turn scenery and selfies into Makoto Shinkai anime art.',
    iconName: 'WandSparkles',
    gradient: ['#8B5CF6', '#6D28D9'],
    isComingSoon: false,
  },
  {
    id: 'style-transfer',
    name: 'Style Transfer',
    category: 'style',
    description: 'Paint your photos in artistic painterly styles.',
    iconName: 'Brush',
    gradient: ['#06B6D4', '#0284C7'],
    isComingSoon: false,
  },
];
